version: '3.8'

services:
  # Aplicación Laravel corriendo en Apache
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: prolecom-app
    container_name: prolecom-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
    networks:
      - prolecom

  # Base de Datos (MySQL)
  db:
    image: mysql:8.0
    container_name: prolecom-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: prolecom_db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: prolecom_user
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - prolecom

networks:
  prolecom:
    driver: bridge

volumes:
  dbdata:
    driver: local
