sonar.projectKey=prolecom_backend
sonar.projectName=Prolecom MVP
sonar.projectVersion=1.0

# Archivos a incluir en el análisis
sonar.sources=app,routes
sonar.tests=tests

# Lenguaje principal
sonar.language=php
sonar.sourceEncoding=UTF-8

# Ruta del reporte de cobertura generado por PHPUnit
sonar.php.coverage.reportPaths=build/logs/clover.xml

# Excluir archivos innecesarios del análisis
sonar.exclusions=vendor/**,storage/**,bootstrap/**,public/**
